### ISSUE TITLE
License

### ISSUE THREAD

**Issue by theCALiC0** [theNestruo/msx-msxlib#2]
What license is applicable for the code in this repo?

I would guess as it's all ASM that would be included in a finalized game it would be MIT, BSD-3-clause, MAYBE CC0, or something similar, but I do not see a license in the repo so I wanted to ask.

Thank you!

**Comment by theNestruo** [comment]
Yup; it's missing. I'll review the details of the different licenses as soon as possible to put the license that best suits the purpose of MSXlib.

The idea is that everyone can use any routine the way they want: copy into their own projects, use MSXlib directly, just as a base for their own libraries... So I'll go for a very permissive license.

Thanks for reporting!

**Comment by theNestruo** [comment]
I finally set the BSD-3-Clause license (one of your suggestions). Thanks!

**Comment by theCALiC0** [comment]
No problem! That's my personal choice these days as well :)

Thank you for your work on this lib as well! Reading the assembly has helped me understand the Z80 quite a bit I think
